### Load librarys and heathiar

In [1]:
import os

# Point Python/rpy2 to the Folder wher your R is located  --> healthiar has to be already installed there
os.environ['R_HOME'] = r"C:\Program Files\R\R-4.4.1"

import rpy2.robjects as ro
from rpy2.robjects.packages import importr
from rpy2.robjects import FloatVector, IntVector,globalenv,ListVector, DataFrame, StrVector, BoolVector
from rpy2.robjects import pandas2ri
import pandas as pd
from rpy2.robjects.conversion import localconverter
from types import SimpleNamespace




healhipy = importr("healthiar")

In [9]:
#function which converts rpy2 lists and dataframes to python lists and pandas dataframes
def rpy2_to_py(obj):
    """
    Recursive conversion
    """
    if isinstance(obj, DataFrame):
        with localconverter(ro.default_converter + pandas2ri.converter):
            return ro.conversion.rpy2py(obj)
    
    elif isinstance(obj, ListVector):
        return {name: rpy2_to_py(obj.rx2(name)) for name in obj.names}
    
    elif isinstance(obj, (IntVector, FloatVector, StrVector, BoolVector)):
        if len(obj) == 1:
            return obj[0]  # single elements
        else:
            return list(obj)  # multiple elements
    else:
        return obj  # fallback for other types

### Example 1
Use attribute_health

In [3]:

# Python-style inputs
exp_central = [20, 20]
prop_pop_exp = [0.5, 0.5]
bhd_central = [10]

# Convert to R vectors
r_exp_central = FloatVector(exp_central)
r_prop_pop_exp = FloatVector(prop_pop_exp)
r_bhd_central = FloatVector(bhd_central)

# Call healthiar function
result = healhipy.attribute_health(
    exp_central=r_exp_central,
    prop_pop_exp=r_prop_pop_exp,
    cutoff_central=5,
    rr_central=1.08,
    rr_increment=10,
    erf_shape="linear_log",
    bhd_central=r_bhd_central
)
print(result.rx2('health_main').rx2('impact'))





result.rx2('health_main')

[1] 0.927071

<rpy2.robjects.vectors.DataFrame object at 0x000001A074B47748> [RTYPES.VECSXP]
R classes: ('tbl_df', 'tbl', 'data.frame')
[StrSexpVe..., StrSexpVe..., StrSexpVe..., StrSexpVe..., ..., BoolSexpV..., StrSexpVe..., FloatSexp..., FloatSexp...]
  geo_id_micro: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x000001A074B47808> [RTYPES.STRSXP]
R classes: ('character',)
['a']
  erf_ci: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x000001A074B34B88> [RTYPES.STRSXP]
R classes: ('character',)
['central']
  exp_ci: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x000001A074B3ABC8> [RTYPES.STRSXP]
R classes: ('character',)
['central']
  bhd_ci: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x000001A074B34E08> [RTYPES.STRSXP]
R classes: ('character',)
['central']
...
  exp_category: <class 'rpy2.robjects.vectors.BoolVector'>
  <rpy2.robjects.vectors.BoolVector object at 0x000001A07A3E8048> [RTYPES.LGLSXP]
R classes: ('logical',)
[       0]
  sex: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x000001A074B6D208> [RTYPES.STRSXP]
R classes: ('character',)
['paf']
  age_group: <class 'rpy2.robjects.vectors.FloatVector'>
  <rpy2.robjects.vectors.FloatVector object at 0x000001A074B6D2C8> [RTYPES.REALSXP]
R classes: ('numeric',)
[1.102180]
  impact: <class 'rpy2.robjects.vectors.FloatVector'>
  <rpy2.robjects.vectors.FloatVector object at 0x000001A074B6D408> [RTYPES.REALSXP]
R classes: ('numeric',)
[0.092707]

In [12]:
py_result = rpy2_to_py(result)
py_result["health_detailed"]["results_raw"].T

                                       1
approach_risk              relative_risk
rr_increment                          10
erf_shape                     linear_log
prop_pop_exp                         0.5
geo_id_micro                           a
age_group                            all
sex                                  all
exp_length                             2
exp_category                        1, 2
exp_type           exposure_distribution
exp_ci                           central
exp                                 20.0
bhd_ci                           central
bhd                                 10.0
cutoff_ci                        central
cutoff                                 5
erf_ci                           central
rr                                  1.08
is_lifetable                       False
pop_fraction_type                    paf
rr_at_exp                        1.10218
pop_fraction                    0.092707
impact                          0.927071
impact_rounded                       1.0

### Example 2:
Use compare with atribute_health inputs

In [13]:
#check if compare works

# Call healthiar function
result1 = healhipy.attribute_health(
    exp_central=8.85,
    cutoff_central=5,
    rr_central=1.118,
    rr_lower = 1.060,
    rr_upper = 1.179,
    rr_increment=10,
    erf_shape="log_linear",
    bhd_central=25000,
    approach_risk = "relative_risk"
)


# Call healthiar function
result2 = healhipy.attribute_health(
    exp_central=6,
    cutoff_central=5,
    rr_central=1.118,
    rr_lower = 1.060,
    rr_upper = 1.179,
    rr_increment=10,
    erf_shape="log_linear",
    bhd_central=25000,
    approach_risk = "relative_risk"
)

As long as result1 and result2 stay in rpy2 format the can be used in healthypy
Afterwards we need to transfom it back to python

In [15]:
compared_r = rpy2_to_py(healhipy.compare(result1,result2,approach_comparison = "delta"))
compared_r["health_main"]

,geo_id_micro,erf_ci,exp_ci,bhd_ci,cutoff_ci,exp_category,sex,age_group,impact_scen_1,impact_scen_2,...,is_lifetable,pop_fraction_type,rr_at_exp_scen_1,pop_fraction_scen_1,prop_pop_exp_scen_2,exp_scen_2,rr_at_exp_scen_2,pop_fraction_scen_2,impact_scen_1_rounded,impact_scen_2_rounded
1,a,central,central,central,central,1,all,all,1050.860466,277.304018,...,False,paf,1.043879,0.042034,1.0,6,1.011217,0.011092,1051.0,277.0
2,a,lower,central,central,central,1,all,all,554.594229,145.248685,...,False,paf,1.022687,0.022184,1.0,6,1.005844,0.005810,555.0,145.0
3,a,upper,central,central,central,1,all,all,1535.722093,408.295694,...,False,paf,1.065449,0.061429,1.0,6,1.016603,0.016332,1536.0,408.0

### Access healthiar documentation

In [23]:
?healhipy.attribute_health

Signature:       healhipy.attribute_health(*args, **kwargs)
Type:            DocumentedSTFunction
String form:
function (approach_risk = "relative_risk", exp_central, exp_lower = NULL,
           exp_upper = NULL,  <...> put_args)
           return(output)
           }
           <bytecode: 0x000001a0765f3370>
           <environment: namespace:healthiar>

File:            c:\users\ardigi\.conda\envs\myenv\lib\site-packages\rpy2\robjects\functions.py
Docstring:
Wrapper around an R function.

The docstring below is built from the R documentation.

description
-----------


 This function calculates the attributable health impacts (mortality or morbidity) due to
 exposure to an environmental stressor (air pollution or noise), using either relative risk ( RR ) or absolute risk ( AR ).

 Arguments for both  RR & AR  pathways

     approach_risk
     exp_central ,  exp_lower ,  exp_upper
     cutoff_central ,  cutoff_lower ,  cutoff_upper
     erf_eq_central ,  erf_eq_lower ,  erf_eq_upper

 Arguments only for  RR  pathways

     rr_central ,  rr_lower ,  rr_upper
     rr_increment
     erf_shape
     bhd_central ,  bhd_lower ,  bhd_upper
     prop_pop_exp

  Argument for  AR  pathways

     pop_exp

   Optional  arguments for both  RR & AR  pathways

     geo_id_micro ,  geo_id_macro ,
     age_group ,  sex ,  info ,  population
     dw_central ,  dw_lower ,  dw_upper
     duration_central ,  duration_lower ,  duration_upper




attribute_health(
    approach_risk = relative_risk,
    exp_central,
    exp_lower = rinterface.NULL,
    exp_upper = rinterface.NULL,
    cutoff_central = 0.0,
    cutoff_lower = rinterface.NULL,
    cutoff_upper = rinterface.NULL,
    pop_exp = rinterface.NULL,
    erf_eq_central = rinterface.NULL,
    erf_eq_lower = rinterface.NULL,
    erf_eq_upper = rinterface.NULL,
    rr_central = rinterface.NULL,
    rr_lower = rinterface.NULL,
    rr_upper = rinterface.NULL,
    rr_increment = rinterface.NULL,
    erf_shape = rinterface.NULL,
    bhd_central = rinterface.NULL,
    bhd_lower = rinterface.NULL,
    bhd_upper = rinterface.NULL,
    prop_pop_exp = 1.0,
    geo_id_micro = a,
    geo_id_macro = rinterface.NULL,
    age_group = all,
    sex = all,
    dw_central = rinterface.NULL,
    dw_lower = rinterface.NULL,
    dw_upper = rinterface.NULL,
    duration_central = rinterface.NULL,
    duration_lower = rinterface.NULL,
    duration_upper = rinterface.NULL,
    info = rinterface.NULL,
    population = rinterface.NULL,
)

Args:
   approach_risk :  'String value' specifying the *risk method*. Options:
  '"relative_risk"' (default) or '"absolute_risk"'.

   Default :  0. See Details for more info.

   pop_exp :  'Numeric vector' specifying the absolute size of the
  *population(s) exposed* to each exposure category. See
  Details for more info. _Only applicable in AR pathways;
  always required._

   rr_increment :  'Numeric value' specifying the *exposure increment* for
  which the provided relative risk is valid. See Details for
  more info. _Only applicable in RR pathways; not required if
  'erf_eq_...' argument(s) already specified._

   erf_shape :  'String value' specifying the *exposure-response function
  shape* to be assumed. Options (no default): '"linear"',
  'log_linear'", '"linear_log"', '"log_log"'. _Only applicable
  in RR pathways; not required if 'erf_eq_...' argument(s)
  already specified._

   prop_pop_exp :  'Numeric value' or 'numeric vector' specifying the
  *population fraction(s) exposed* for each exposure
  (category). Default: 1. See Details for more info. _Only
  applicable in RR pathways._

   age_group :  'Numeric vector' or 'string vector' providing the *age
  groups* considered in the assessment. In case of use in
  'attribute_lifetable)()', it must be a 'numeric' and contain
  single year age groups. See Details for more info. _Optional
  argument for 'attribute_health()'; needed for
  'attribute_lifetable()'._

   sex :  'Numeric vector' or 'string vector' specifying the *sex* of
  the groups considered in the assessment._Optional argument._

   info :  'String', 'data frame' or 'tibble' providing *information
  about the assessment*. See Details for more info. _Optional
  argument._

   population :  'Numeric vector' *'For attribute_lifetable()'*, it is an
  _obligatory argument_ specifying the *mid-year populations*
  per age (i.e. age group size = 1 year) for the (first) year
  of analysis. *'For attribute_health()'* it is an _optional
  argument_ which specifies the *population used to calculate
  attributable impacts rate* per 100 000 population. See
  Details for more info.

details
-------


 What you put in is what you get out

 The health metric you put in (e.g. absolute disease cases, deaths per 100 000 population, DALYs, prevalence, incidence, ...) is the one you get out.

 Exception : if you enter a disability weight (via the  dw_...  arguments) the attributable impact will be in YLD.

 Function arguments

 exp_central ,  exp_lower ,  exp_upper

 In case of exposure bands enter only one exposure value per band (e.g. the means of the lower and upper bounds of the exposure bands).

 cutoff_central ,  cutoff_lower ,  cutoff_upper

 The cutoff level refers to the exposure level below which no health effects occur in the same unit as the exposure. If exposure categories are used, the length of this input must be the same as in the  exp_...  argument(s).

 pop_exp

 Only applicable in AR pathways; always required.  In AR pathways the population exposed per exposure category is multiplied with the corresonding category-specific risk to obtain the absolute number of people affected by the health outcome.

 erf_eq_central ,  erf_eq_lower ,  erf_eq_upper

 Required in AR pathways; in RR pathways required only if rr_... arguments not specified.  Enter the exposure-response function as a  function , e.g. output from  stats::splinefun()  or  stats::approxfun() , or as a  string  formula, e.g.  "3+c+c^2"  (with the  c  representing the concentration/exposure).

 If you have x-axis (exposure) and y-axis (relative risk) value pairs of multiple points lying on the the exposure-response function, you could use e.g.  stats::splinefun(x, y, method="natural")  to derive the exposure-response function (in this example using a cubic spline natural interpolation).

 rr_increment

 Only applicable in RR pathways.  Relative risks from the literature are valid for a specific increment in the exposure, in case of air pollution often 10 or 5  \mu g/m^3 ).

 bhd_central ,  bhd_lower ,  bhd_upper

 Only applicable in RR pathways.  Baseline health data for each exposure category must be entered.

 prop_pop_exp

 Only applicable in RR pathways.  In RR pathways indicates the fraction(s) (value(s) from 0 until and including 1) of the total population exposed to the exposure categories. See equation of the population attributable fraction for categorical exposure below.

 geo_id_macro ,  geo_id_micro

 Only applicable in assessments with multiple geographic units.  For example, if you provide the names of the municipalities under analysis to  geo_id_micro , you might provide to  geo_id_macro  the corresponding region / canton / province names.
 Consequently, the vectors fed to  geo_id_micro  and  geo_id_macro  must be of the same length.

 age_group

 Can be either  numeric  or  character . If it is numeric, it refers to the first age of the age group. E.g.  c(0, 40, 80)  means age groups  [0, 40), [40, 80), >=80] .

 info

 Optional argument.  Information entered to this argument will be added as column(s) names  info_1 ,  info_2 ,  info_...  to the results table. These additional columns can be used to further stratify the analysis in a secondary step (see example below).

 population

 Optional argument.  The population entered here is used to determine impact rate per 100 000 population. Note the requirement for the vector length in the paragraph  Assessment of multiple geographic units  below.

 duration_central ,  duration_lower ,  duration_upper

 Only applicable in assessments of YLD (years lived with disability).  If the value of  duration_central  is 1 year, it refers to the prevalence-based approach, while a value above 1 year to the incidence-based approach (Kim et al. 2022, https://doi.org/10.3961/jpmph.21.597).

 Assessment of multiple geographic units

 To assess the attributable health impact/burden across multiple geographic units with  attribute_health() , you must specify the argument  geo_id_micro  and (optionally)  geo_id_macro , in addition to the other required function arguments.

 The length of the input vectors to the function arguments must be:

 \text{length input vectors} = \text{number of geo units} \times \text{number of exposure categories}

 (  \times \text{number of age groups (if entered)} \times \text{number of sex groups (if entered) )}

 I.e. there must be one line / observation for each specific combination of geo unit, exposure category, age and sex group.

 Alternatively, for those arguments that are independent of location (e.g.  approach_risk ,  rr_... ,  erf_shape , ...), you can enter a single value, which will be recycled to match the length of the other geo unit-specific input data. Additional categories can be passed on via the  info  argument.

 Equations (relative risk)

 The most general equation describing the population attributable fraction (PAF) mathematically is an integral form (GBD 2019 Risk Factors Collaborators 2020, https://doi.org/10.1016/S0140-6736(20)30752-2):
 PAF = \frac{\int RR(x)PE(x)dx - 1}{\int RR(x)PE(x)dx}

 Where:

 x  = exposure level

 PE(x)  = population distribution of exposure

 RR(x)  = relative risk at exposure level compared to the reference level

 If the population exposure is described as a categorical rather than continuous exposure, the integrals in this equation may be converted to sums, resulting in the following equation for the PAF (WHO 2003a, https://www.who.int/publications/i/item/9241546204; WHO 2011, https://iris.who.int/items/723ab97c-5c33-4e3b-8df1-744aa5bc1c27):
 PAF = \frac{\sum RR_i \times PE_i - 1}{\sum RR_i \times PE_i}

 Where:

 i  = is the exposure category (e.g. in bins of 1  \mu g/m^3  PM2.5 or 5 dB noise exposure)

 PE_i  = fraction of population in exposure category i

 RR_i  = relative risk associated with the mean exposure level in exposure category i compared to the reference level

 There is one alternative for the PAF for categorical exposure distribution that is commonly used, which is mathematically equivalent to the equation right above, meaning that numerical estimates based on these equations are identical (WHO 2003b, https://doi.org/10.1186/1478-7954-1-1; WHO 2011, https://iris.who.int/items/723ab97c-5c33-4e3b-8df1-744aa5bc1c27):
 PAF = \frac{\sum PE_i(RR_i - 1)}{\sum PE_i(RR_i - 1) + 1}

 Where:

 i  = is the exposure category (e.g. in bins of 1  \mu g/m^3  PM2.5 or 5 dB noise exposure)

 PE_i  = fraction of population in exposure category i

 RR_i  = relative risk associated with the mean exposure level in exposure category i compared to the reference level

 Finally, if the exposure is provided as the population weighted mean concentration (PWC), the equation for the PAF is reduced to (ETC HE 2022, https://www.eionet.europa.eu/etcs/all-etc-reports:
 PAF = \frac{RR_{PWC} - 1}{RR_{PWC}}
 Where  RR_{PWC}  is the relative risk associated with the population weighted mean exposure.

 Equation (absolute risk)
 N = \sum AR_i\times PE_i

 Where:

 N  = the number of cases of the exposure-specific health outcome that are attributed to the exposure

 AR_i  = absolute risk associated with the mean exposure level of exposure category i

 PE_i  = population exposed (absolute number) to exposure levels of exposure category i

 Conversion of alternative risk measures to relative risks
 For conversion of hazard ratios and/or odds ratios to relative risks refer to VanderWeele 2019 (https://doi.org/10.1111/biom.13197) and/or use the conversion tools developed by the Teaching group in EBM in 2022 for hazard ratios (https://ebm-helper.cn/en/Conv/HR_RR.html) and/or odds ratios (https://ebm-helper.cn/en/Conv/OR_RR.html).


Class docstring:
Python representation of an R function, where
the names in named argument are translated to valid
argument names in Python.